import { useEffect, useMemo, useState } from 'react'
import { Brain, Lightbulb, RefreshCw, TrendingUp, Package, IndianRupee } from 'lucide-react'
import { Line, Bar, Doughnut } from 'react-chartjs-2'
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, BarElement, ArcElement, Tooltip, Legend } from 'chart.js'
import toast from 'react-hot-toast'
import { getAiAnalytics } from '../services/analyticsService'
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, BarElement, ArcElement, Tooltip, Legend)

type Analytics = { todaySales:number; todayProfit:number; monthlyForecast:number; annualForecast:number; lowStockAlerts:number; revenueTrend:Record<string,number>; topSellingProducts:any[]; leastSellingProducts:any[]; inventorySuggestions:any[]; businessSuggestions:string[]; categoryAnalysis:Record<string,number>; deadStock:any[] }
const money = (v:number) => `Rs.${Number(v || 0).toLocaleString(undefined,{maximumFractionDigits:2})}`
const Card = ({title,value,icon:Icon}:{title:string;value:React.ReactNode;icon:any}) => <div className="card"><div className="flex justify-between items-start"><div><p className="text-sm text-gray-500">{title}</p><p className="text-xl font-bold mt-1">{value}</p></div><Icon className="w-5 h-5 text-blue-600"/></div></div>
export default function AiAnalytics() {
 const [data,setData]=useState<Analytics|null>(null); const [loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);try{setData(await getAiAnalytics())}catch{toast.error('Unable to generate AI analytics')}finally{setLoading(false)}}; useEffect(()=>{void load()},[])
 const trend=useMemo(()=>data?{labels:Object.keys(data.revenueTrend),datasets:[{label:'Revenue trend',data:Object.values(data.revenueTrend),borderColor:'#2563eb',backgroundColor:'rgba(37,99,235,.12)',fill:true,tension:.35}]}:null,[data])
 if(loading)return <div className="text-center py-20">Calculating analytics…</div>; if(!data)return <div className="text-center py-20">No analytics available</div>
 const products=data.topSellingProducts||[]; const categories=Object.entries(data.categoryAnalysis||{}); return <div className="space-y-6">
  <div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><Brain className="w-6 h-6 text-blue-600"/><h1 className="text-2xl font-bold">AI business intelligence</h1></div><p className="text-sm text-gray-500">Explainable local forecasts based on the last 30 days of sales.</p></div><button className="btn-secondary" onClick={load}><RefreshCw className="inline w-4 h-4 mr-1"/>Refresh</button></div>
  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4"><Card title="Today's sales" value={money(data.todaySales)} icon={IndianRupee}/><Card title="Today's profit" value={money(data.todayProfit)} icon={TrendingUp}/><Card title="Monthly forecast" value={money(data.monthlyForecast)} icon={TrendingUp}/><Card title="Annual forecast" value={money(data.annualForecast)} icon={TrendingUp}/><Card title="Low stock alerts" value={data.lowStockAlerts} icon={Package}/></div>
  <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="card lg:col-span-2"><h2 className="font-semibold mb-4">Revenue trend & monthly prediction</h2><div className="relative h-64">{trend&&<Line data={trend} options={{responsive:true,maintainAspectRatio:false}} />}</div></div><div className="card"><h2 className="font-semibold mb-4">Category profit analysis</h2><div className="relative h-64"><Doughnut data={{labels:categories.map(([k])=>k),datasets:[{data:categories.map(([,v])=>v),backgroundColor:['#2563eb','#10b981','#f59e0b','#ef4444','#8b5cf6'],borderWidth:0}]}} options={{responsive:true,maintainAspectRatio:false}} /></div></div></div>
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><div className="card"><h2 className="font-semibold mb-4">Top product sales prediction</h2><div className="relative h-56"><Bar data={{labels:products.map(p=>p.productName),datasets:[{label:'Units sold (30 days)',data:products.map(p=>p.quantity),backgroundColor:'#10b981'}]}} options={{responsive:true,maintainAspectRatio:false}} /></div></div><div className="card"><h2 className="font-semibold mb-4">Inventory forecast (days remaining)</h2><div className="relative h-56"><Bar data={{labels:(data.inventorySuggestions||[]).map(p=>p.productName),datasets:[{label:'Days remaining',data:(data.inventorySuggestions||[]).map(p=>p.daysRemaining===999?0:p.daysRemaining),backgroundColor:'#f59e0b'}]}} options={{responsive:true,maintainAspectRatio:false}} /></div></div></div>
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><div className="card"><h2 className="font-semibold mb-3">Top / fast-moving products</h2><div className="space-y-2">{products.map(p=><div key={p.productId} className="flex justify-between border-b border-gray-100 dark:border-gray-700 py-2"><span>{p.productName}</span><span className="font-medium">{p.quantity} sold · {money(p.profit)} profit</span></div>)}</div></div><div className="card"><h2 className="font-semibold mb-3">Least-selling / slow-moving</h2><div className="space-y-2">{(data.leastSellingProducts||[]).map(p=><div key={p.productId} className="flex justify-between border-b border-gray-100 dark:border-gray-700 py-2"><span>{p.productName}</span><span className="font-medium">{p.quantity} sold</span></div>)}{data.deadStock?.length>0&&<p className="text-sm text-red-600 mt-3">Dead stock: {data.deadStock.map(p=>p.productName).join(', ')}</p>}</div></div></div>
  <div className="card"><h2 className="font-semibold mb-3">Inventory suggestions</h2><div className="grid md:grid-cols-2 gap-3">{(data.inventorySuggestions||[]).map(p=><div key={p.productId} className="p-3 rounded-lg bg-amber-50 dark:bg-amber-950/30"><p className="font-medium">{p.productName} · {p.daysRemaining===999?'No recent sales':`${p.daysRemaining} days remaining`}</p><p className="text-sm text-gray-600 dark:text-gray-300">{p.recommendation}</p></div>)}{!data.inventorySuggestions?.length&&<p className="text-sm text-gray-500">Inventory levels look healthy.</p>}</div></div>
  <div className="card"><h2 className="font-semibold mb-3"><Lightbulb className="inline w-5 h-5 text-amber-500 mr-1"/>Business suggestions</h2><ul className="list-disc pl-5 space-y-2">{(data.businessSuggestions||[]).map((s,i)=><li key={i}>{s}</li>)}</ul></div>
  <div className="card"><h2 className="font-semibold mb-3">AI daily report</h2><p className="text-sm text-gray-600 dark:text-gray-300">Today’s sales are {money(data.todaySales)} with estimated profit of {money(data.todayProfit)}. There are {data.lowStockAlerts} low-stock alerts. Review the recommended actions above before the next supplier order.</p></div>
 </div>
}
