import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { Download, Plus, Search } from 'lucide-react'
import { Product, Purchase } from '../types'
import { getProducts } from '../services/productService'
import { createPurchase, getPurchases } from '../services/purchaseService'
import { exportReport } from '../services/reportService'

const today = new Date().toISOString().slice(0, 10)
export default function Purchases() {
 const [items,setItems]=useState<Purchase[]>([]); const [products,setProducts]=useState<Product[]>([]); const [show,setShow]=useState(false); const [filters,setFilters]=useState({from:'',to:'',supplier:'',productId:''});
 const [form,setForm]=useState({supplierName:'',invoiceNumber:'',purchaseDate:today,productId:'',quantity:1,purchasePrice:0,gstPercentage:0,expiryDate:'',batchNumber:''})
 const load=async()=>{try{setItems(await getPurchases(filters))}catch{toast.error('Unable to load purchases')}}
 useEffect(()=>{getProducts().then(setProducts).catch(()=>toast.error('Unable to load products'));load()},[])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{await createPurchase({...form,productId:Number(form.productId),quantity:Number(form.quantity),purchasePrice:Number(form.purchasePrice),gstPercentage:Number(form.gstPercentage),expiryDate:form.expiryDate||undefined});toast.success('Purchase saved; stock updated');setShow(false);load()}catch(e:any){toast.error(e.response?.data?.message||'Purchase could not be saved')}}
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Purchase history</h1><p className="text-sm text-gray-500">Every stock increase is recorded against an invoice.</p></div><div className="flex gap-2"><button onClick={()=>exportReport('purchase','xlsx')} className="btn-secondary"><Download className="inline w-4 h-4 mr-1"/>Excel</button><button onClick={()=>exportReport('purchase','pdf')} className="btn-secondary">PDF</button><button onClick={()=>setShow(true)} className="btn-primary"><Plus className="inline w-4 h-4 mr-1"/>New purchase</button></div></div>
 <div className="card grid grid-cols-1 md:grid-cols-5 gap-3"><input type="date" className="input-field" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input type="date" className="input-field" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/><input className="input-field" placeholder="Supplier" value={filters.supplier} onChange={e=>setFilters({...filters,supplier:e.target.value})}/><select className="input-field" value={filters.productId} onChange={e=>setFilters({...filters,productId:e.target.value})}><option value="">All products</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="btn-primary" onClick={load}><Search className="inline w-4 h-4 mr-1"/>Filter</button></div>
 <div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-left">Date</th><th className="p-3 text-left">Supplier</th><th className="p-3 text-left">Invoice</th><th className="p-3 text-left">Product</th><th className="p-3 text-right">Qty</th><th className="p-3 text-right">GST</th><th className="p-3 text-right">Total cost</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className="border-b border-gray-100 dark:border-gray-700"><td className="p-3">{i.purchaseDate}</td><td className="p-3">{i.supplierName}</td><td className="p-3 font-mono">{i.invoiceNumber}</td><td className="p-3">{i.productName}{i.batchNumber&&<span className="block text-xs text-gray-500">Batch {i.batchNumber}</span>}</td><td className="p-3 text-right">{i.quantity}</td><td className="p-3 text-right">{i.gstPercentage}%</td><td className="p-3 text-right font-medium">Rs.{Number(i.totalCost).toFixed(2)}</td></tr>)}</tbody></table>{!items.length&&<p className="py-8 text-center text-gray-500">No purchases match these filters.</p>}</div>
 {show&&<div className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><form onSubmit={submit} className="bg-white dark:bg-gray-800 p-6 rounded-xl w-full max-w-2xl space-y-4 max-h-[90vh] overflow-auto"><h2 className="text-xl font-bold">Add purchase</h2><div className="grid md:grid-cols-2 gap-4"><input required className="input-field" placeholder="Supplier name" value={form.supplierName} onChange={e=>setForm({...form,supplierName:e.target.value})}/><input required className="input-field" placeholder="Invoice number" value={form.invoiceNumber} onChange={e=>setForm({...form,invoiceNumber:e.target.value})}/><input required type="date" className="input-field" value={form.purchaseDate} onChange={e=>setForm({...form,purchaseDate:e.target.value})}/><select required className="input-field" value={form.productId} onChange={e=>setForm({...form,productId:e.target.value})}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input required min="1" type="number" className="input-field" placeholder="Quantity" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/><input required min="0" step="0.01" type="number" className="input-field" placeholder="Purchase price" value={form.purchasePrice} onChange={e=>setForm({...form,purchasePrice:Number(e.target.value)})}/><input required min="0" step="0.01" type="number" className="input-field" placeholder="GST %" value={form.gstPercentage} onChange={e=>setForm({...form,gstPercentage:Number(e.target.value)})}/><input type="date" className="input-field" value={form.expiryDate} onChange={e=>setForm({...form,expiryDate:e.target.value})}/><input className="input-field" placeholder="Batch number" value={form.batchNumber} onChange={e=>setForm({...form,batchNumber:e.target.value})}/></div><div className="flex gap-2"><button className="btn-primary flex-1">Save purchase</button><button type="button" onClick={()=>setShow(false)} className="btn-secondary flex-1">Cancel</button></div></form></div>}</div>
}
